#!/usr/bin/env bash

set -eu -o pipefail

echo 'deb-src http://mirrors.kernel.org/debian/ bookworm main contrib' > /etc/apt/sources.list.d/src.list
apt-get update -y
apt-get dist-upgrade -y
apt-get install -y sbcl git curl libzstd-dev
