#!/usr/bin/env bash
set -eu -o pipefail

cd /sbcl-build

apt-get build-dep -y sbcl
./make.sh --fancy --prefix=/usr/local/ --with-sb-linkable-runtime --with-sb-dynamic-core --arch=x86-64
./install.sh

cd /root

curl https://beta.quicklisp.org/quicklisp.lisp -Oquicklisp.lisp
/usr/local/bin/sbcl --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --quit
rm quicklisp.lisp

rm -rf /sbcl-build

/setup/cleanup

