#!/usr/bin/env bash
set -eu -o pipefail

git clone git://git.code.sf.net/p/sbcl/sbcl /sbcl-build
   
cd /sbcl-build

if [[ "${version:-"$DOCKER_TAG"}" == "latest" ]]; then
  version=master
fi

echo building version $version

git checkout "${version}"
