#!/usr/bin/env bash
set -eu -o pipefail

git clone git://git.code.sf.net/p/sbcl/sbcl /sbcl-build
   
cd /sbcl-build

if [[ "$version" == "latest" ]]; then
  version=master
fi

git checkout "${version}"
